

sequenceDiagram

    Actor User 
    participant zEVM 
    participant ZRC20
    participant Observer 
    participant Zetachain 
    participant Chain2

    User->>Zetachain: Calls contract to withdraw funds 
    Zetachain->>ZRC20: Withdraw is called. Emits an event. 
    Zetachain->>Zetachain: Creates a new outbound transaction
    Observer->>Observer: TSS Signing ceremony
    Observer->>Chain2: Deposit funds to receiver using TSS
    loop Until quorum
        Observer->>Zetachain: Vote on transfer event occurence
    end
    Zetachain->>Zetachain: Emit outbound tx voting succeeded
